version: 2
nightly:
  triggers:
    - schedule:
        cron: "0 0 * * *"
jobs:
  build:
    docker:
      - image: buildpack-deps:bionic
    steps:
      - run:
          name: Update APT
          command: apt update
      - run:
          name: Install Dependencies
          command: apt install -y sudo reprepro
      - checkout
      - run:
          name: Build MCPELauncher
          command: ./build-mcpe.sh
      - run:
          name: Import Key
          command: openssl aes-256-cbc -d -in repo/conf/private -k ${GITHUB_TOKEN} | gpg --batch --import -
      - run:
          name: Cleanup
          command: rm repo/conf/private
      - run:
          name: Build Repo
          command: reprepro -b repo includedeb bionic mcpe-build/out/*.deb
      - run:
          name: Deploy To Github Pages
          command: ./deploy.sh
